export {
  dedupeKey,
  fingerprint,
  hasSomethingToClassify,
  type ClassificationInput,
} from './fingerprint.js';
export {
  AUTO_ACCEPT_CONFIDENCE,
  decideFromAi,
  decideFromHuman,
  decideFromMemory,
  decideUnclassifiable,
  isValuable,
  type AiAnswer,
  type Decision,
  type MemoryRecord,
} from './decide.js';
export {
  bundledComponents,
  includedComponents,
  type BundleSignal,
  type IncludedSignal,
} from './bundles.js';
export {
  CLASSIFICATION_KEYS,
  EXCLUSION_CATEGORIES,
  EXCLUSION_KEYS,
  classificationLabel,
  classificationOptions,
  isExclusion,
  isKnownClassification,
  type ClassificationKey,
  type ClassificationOption,
  type ExclusionKey,
  type ExclusionRule,
} from './vocabulary.js';
export {
  AUTO_ACCEPT_CONFIDENCE as LINE_AUTO_ACCEPT_CONFIDENCE,
  LINE_MAPPING_KEYS,
  WORDING_SCHEDULES,
  isComparable,
  isKnownLineMapping,
  isMixed,
  lineMappingLabel,
  lineTypeFingerprint,
  mapFromAi,
  mapFromHuman,
  mapFromMemory,
  mapFromSchedule,
  mapUnmappable,
  scheduleDecides,
  type LineAnswer,
  type LineMapping,
  type LineMappingKey,
  type LineMemoryRecord,
} from './line-types.js';
