import { mkdir, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { CORPUS } from './catalog.js';
import { business } from './business.js';
import type { CorpusEntry } from './types.js';

/**
 * Write the corpus out as files somebody can actually drop on the product.
 *
 * Grouped by business rather than by format, because that is the unit the
 * product receives: a client sends their register and the two documents that
 * explain it in one go, and the interesting behaviour — the prior return
 * disagreeing with the register, two counties turning into two returns — only
 * appears when they arrive together.
 *
 * The output is regenerated wholesale every run and lives under the repo's
 * ignored `data/` directory. Nothing here is committed: the entries are the
 * source, the files are a rendering of them, and a rendering checked into git
 * is a second copy that starts drifting the day somebody edits one of them.
 */

const OUT = new URL('../../../data/corpus/', import.meta.url);

async function main(): Promise<void> {
  const root = fileURLToPath(OUT);
  await rm(root, { recursive: true, force: true });

  const written: { entry: CorpusEntry; path: string; bytes: number }[] = [];
  for (const entry of CORPUS) {
    const folder = `${root}${entry.businessId}/`;
    await mkdir(folder, { recursive: true });
    const bytes = await entry.build();
    await writeFile(`${folder}${entry.filename}`, bytes);
    written.push({
      entry,
      path: `${entry.businessId}/${entry.filename}`,
      bytes: bytes.byteLength,
    });
  }

  await writeFile(
    `${root}manifest.json`,
    `${JSON.stringify(
      written.map(({ entry, path, bytes }) => ({
        id: entry.id,
        path,
        bytes,
        kind: entry.kind,
        format: entry.format,
        business: business(entry.businessId).name,
        source: entry.source,
        jurisdictions: entry.jurisdictions,
        premise: entry.premise,
        traps: entry.traps,
        expectation: entry.expectation,
        truth: entry.truth,
      })),
      null,
      2,
    )}\n`,
  );
  await writeFile(`${root}README.md`, readme(written));

  const total = written.reduce((sum, one) => sum + one.bytes, 0);
  for (const { path, bytes } of written) {
    console.log(`${path.padEnd(52)} ${(bytes / 1024).toFixed(1).padStart(8)} KB`);
  }
  console.log(`\n${written.length} files, ${(total / 1024).toFixed(0)} KB, in ${root}`);
}

function readme(written: { entry: CorpusEntry; path: string; bytes: number }[]): string {
  const rows = written.map(({ entry, path }) => {
    const bar = entry.expectation.autopilot === 'clears' ? 'clears' : 'holds';
    return `| \`${path}\` | ${entry.kind} | ${entry.format} | ${entry.jurisdictions.join(', ')} | ${bar} | ${entry.premise} |`;
  });
  return [
    '# Corpus',
    '',
    'Generated by `pnpm --filter @tangible/corpus write`. Do not edit these files —',
    'edit the entries in `packages/corpus/src` and regenerate, or the traps stop',
    'matching what the manifest says they are.',
    '',
    'One folder per business. Drop a whole folder on the intake page to see what a',
    'client engagement looks like when the register and the documents arrive together.',
    '',
    '| file | kind | format | jurisdictions | autopilot | what it is |',
    '| --- | --- | --- | --- | --- | --- |',
    ...rows,
    '',
    '## Traps',
    '',
    ...written.flatMap(({ entry, path }) => [
      `### \`${path}\``,
      '',
      ...entry.traps.map((trap) => `- ${trap}`),
      '',
      `**Autopilot ${entry.expectation.autopilot}.** ${entry.expectation.because}`,
      '',
    ]),
  ].join('\n');
}

await main();
